# -*- coding: utf-8 -*-
"""第二批修潤：投影片正文與講稿。"""
from humanize import apply
import sys, io

R = [
# ============================================================ part 1 =====
("slides_part1.py", "每一章都在回答同一個問題的不同層次 —— 這一輪 forward 的成本被多少 token 分攤了。",
 "每一章問的都是同一件事的不同層次：這一輪 forward 的成本被多少 token 分攤了。"),
("slides_part1.py", "模型看到的可能是 20 幾個 token —— 所有容量計算的分母都是這個 T，不是字數。",
 "模型看到的可能是 20 幾個 token。容量計算的分母是這個 T，不是字數。"),
("slides_part1.py", "這一塊主宰了 MTP 起草器的成本 —— 起草一次的代價幾乎就是再讀一次 lm_head。",
 "這一塊主宰了 MTP 起草器的成本：起草一次的代價，幾乎就是再讀一次 lm_head。"),
("slides_part1.py", "\"抽到的 token <b>接回輸入尾端</b>，再跑一次 —— autoregressive 就是這個迴圈。\"",
 "\"抽到的 token <b>接回輸入尾端</b>，再跑一次。autoregressive 就是這個迴圈。\""),
("slides_part1.py", "'一次 forward 前進多格 —— 那是 CH7 的主題，機制上仍然是同一個迴圈。</p>'",
 "'一次 forward 前進多格。那是 CH7 的主題，機制上還是同一個迴圈。</p>'"),
("slides_part1.py", "光讀完就要 10.8 ms —— 如果只服務一個人，\n一秒最多 92 個 token，而且 GPU 的算力幾乎完全閒著。",
 "光讀完就要 10.8 ms。只服務一個人的話，一秒最多 92 個 token，而 GPU 的算力幾乎全閒著。"),
("slides_part1.py", "\"<b>Attention</b> 用本輪的 Q 去查<b>整段歷史</b>的 K/V —— 這是唯一需要跨位置讀取的地方。\"",
 "\"<b>Attention</b> 用本輪的 Q 去查<b>整段歷史</b>的 K/V。整層裡只有這一步要跨位置讀取。\""),
("slides_part1.py", "只有 token mixer 需要記憶體來保存歷史 —— 這決定了 cache 的形狀。",
 "只有 token mixer 需要記憶體保存歷史，cache 的形狀就是這樣決定的。"),
("slides_part1.py", "\"<b>③</b> 但 attention 要<b>讀取全部 8 格</b> —— 讀取量隨 context 線性成長。\"",
 "\"<b>③</b> 但 attention 要<b>讀取全部 8 格</b>，讀取量隨 context 線性成長。\""),
("slides_part1.py", "'② FP8 KV cache 砍一半 ③ 換掉 token mixer，讓它不需要 KV —— 就是 CH4 的 GDN。</p>'",
 "'② FP8 KV cache 砍一半 ③ 換掉 token mixer，讓它不需要 KV，也就是 CH4 的 GDN。</p>'"),
("slides_part1.py", "單卡放不下兩條 —— 這就是為什麼混合架構會出現。",
 "單卡放不下兩條。混合架構會出現，就是為了這件事。"),
("slides_part1.py", "\"下排只有 2 組橘格 —— 16 個 Q head 共用同一組 K/V。\"",
 "\"下排只有 2 組橘格：16 個 Q head 共用同一組 K/V。\""),
("slides_part1.py", "與 122B 的 24 KiB/token 差 10.7 倍 —— 同樣的 HBM 能放的\ncontext 就差 10 倍。這是這一版報告最重要的對照之一。",
 "與 122B 的 24 KiB/token 差 10.7 倍，同樣的 HBM 能放的 context 也就差 10 倍。\n這是這一版最重要的對照之一。"),
("slides_part1.py", "\"左邊 memory-bound：時間等於讀權重的時間，跟 N 無關 —— 多塞 token 幾乎不用加錢。\"",
 "\"左邊 memory-bound：時間等於讀權重的時間，跟 N 無關，多塞 token 幾乎不用加錢。\""),
("slides_part1.py", "\"而 32 併發配上 DFlash2 的 7 個草稿，一次就送進 256 個 token —— \"\n \"剛好貼在轉折點上。這正是 CH7 要算清楚的事。\"",
 "\"而 32 併發配上 DFlash2 的 7 個草稿，一次就送進 256 個 token，\"\n \"剛好貼在轉折點上。CH7 要算的就是這件事。\""),
("slides_part1.py", "f'<b>提高每個 step 的 token 數</b> —— 更大 batch，或 {T(\"Speculative decoding\")}。</p>'",
 "f'<b>提高每個 step 的 token 數</b>：更大 batch，或 {T(\"Speculative decoding\")}。</p>'"),
("slides_part1.py", "{pane(\"唯一的出路\"", "{pane(\"想離開只有一條路\""),
("slides_part1.py", "{pane(\"量化不會救你\"", "{pane(\"量化幫不上這個忙\""),
("slides_part1.py", "「上了 FP4 就不再 memory-bound」是常見誤解。",
 "「上了 FP4 就不再 memory-bound」是很常見的誤會。"),
("slides_part1.py", "'可以拿去猜 token。這正是 speculative decoding 能成立的物理基礎。</p>'",
 "'可以拿去猜 token。speculative decoding 之所以成立，靠的就是這塊。</p>'"),
("slides_part1.py", "看清這件事之後，所有 serving 最佳化都變成同一個動作：",
 "看清這件事之後，serving 上的最佳化就收斂成同一個動作："),
("slides_part1.py", "這是全報告最重要的一頁概念。", "這一頁的概念在全報告裡最重要。"),
("slides_part1.py", "這一頁是第二版新增的核心分析，也是整份報告的樞紐。",
 "這一頁是第二版新增的，也是整份報告的樞紐。"),
("slides_part1.py", "精度不變性是個很漂亮的結果，聽眾通常會意外。它也直接推翻一個常見誤解：\n「上了 FP4 就不再是 memory-bound」。實際上 FP4 讓你讀得更快也算得更快，\n你在 roofline 上的<b>相對位置</b>完全沒動。",
 "精度不變性這個結果很漂亮，聽眾通常會意外。它也推翻了一個常見誤會：\n「上了 FP4 就不再是 memory-bound」。FP4 讓你讀得更快也算得更快，\n但你在 roofline 上的<b>相對位置</b>沒有動。"),
("slides_part1.py", "這個不對稱是後面所有故事的起點。", "後面所有的事情都從這個不對稱長出來。"),
("slides_part1.py", "這是 decode 慢的唯一根本原因", "decode 之所以慢，原因就在這裡"),

# ============================================================ part 2 =====
("slides_part2.py", "\"<b>Kernels</b> 才是真正動手的地方 —— 量化 kernel 就掛在這一層。\"",
 "\"<b>Kernels</b> 才是真正動手的地方，量化 kernel 就掛在這一層。\""),
("slides_part2.py", "每個 step 分成三段 —— schedule、forward pass、postprocess。",
 "每個 step 分成三段：schedule、forward pass、postprocess。"),
("slides_part2.py", "\"紅色格子就是純粹的浪費 —— 而且它同時浪費算力<b>和</b>頻寬。\"",
 "\"紅色格子是純粹的浪費，而且算力和頻寬一起浪費。\""),
("slides_part2.py", "notes=\"<p>如果時間緊，這一頁可以跳過 —— 前一頁的動畫已經涵蓋。</p>\"",
 "notes=\"<p>時間緊的話這一頁可以跳過，前一頁的動畫已經講完了。</p>\""),
("slides_part2.py", "\"<b>block table</b> 記住邏輯到實體的對應 —— 就像作業系統的分頁表。\"",
 "\"<b>block table</b> 記住邏輯到實體的對應，就像作業系統的分頁表。\""),
("slides_part2.py", "physical block ——\n   這就是 prefix caching 的實作基礎。</li>",
 "physical block，\n   prefix caching 就是靠這個做的。</li>"),
("slides_part2.py", "<li>副作用：那個長 prompt 自己的 TTFT 變長 —— 這是刻意的取捨。</li>",
 "<li>副作用：那個長 prompt 自己的 TTFT 會變長，這是刻意的取捨。</li>"),
("slides_part2.py", "會干擾命中率 —— CH7 有實測案例。</li>",
 "會干擾命中率，CH7 有實測案例。</li>"),
("slides_part2.py", "但一定要重新量接受率 —— CH7 會說明為什麼。",
 "但一定要重新量接受率，CH7 會說明為什麼。"),
("slides_part2.py", "\"所以 KV/token 差了一個數量級 —— 這是後面所有記憶體帳本的根源。\"",
 "\"所以 KV/token 差了一個數量級。後面的記憶體帳本都從這裡長出來。\""),
("slides_part2.py", "KiB 的 KV cache —— \"\n      f\"比 122B 高",
 "KiB 的 KV cache，\"\n      f\"比 122B 高"),
("slides_part2.py", "GB\n  ——這些空間全部可以拿去放 cache。</p>",
 "GB，\n  這些空間全部可以拿去放 cache。</p>"),
("slides_part2.py", "③ MTP head 有 2.52 B 參數而且沒被量化，會吃掉 5 GB —— 這個細節在第一版報告完全沒有提到。",
 "③ MTP head 有 2.52 B 參數而且沒被量化，會吃掉 5 GB。第一版報告完全沒提到這件事。"),
("slides_part2.py", "\"算力面：每 token 只啟用 9.0 B 參數 —— 這是型號裡「A10B」的意思。\"",
 "\"算力面：每 token 只啟用 9.0 B 參數，型號裡的「A10B」講的就是這個。\""),
("slides_part2.py", "\"而且 batch 一大，被選到的 expert 幾乎涵蓋全部 256 個 —— 記憶體流量會從 2 GB 長到 65 GB。\"",
 "\"而且 batch 一大，被選到的 expert 幾乎涵蓋全部 256 個，記憶體流量從 2 GB 長到 65 GB。\""),
("slides_part2.py", "記憶體從隨 context 線性成長變成常數 —— 代價是這個矩陣是有損壓縮。",
 "記憶體從隨 context 線性成長變成常數。代價是這個矩陣屬於有損壓縮。"),
("slides_part2.py", "[\"資訊保真度\", \"無損\", \"有損 —— 越長越糊\"],",
 "[\"資訊保真度\", \"無損\", \"有損，越長越糊\"],"),
("slides_part2.py", "\"更新完，S 的大小<b>完全沒變</b> —— 這是整件事的重點。\"",
 "\"更新完，S 的大小<b>沒有變</b>。整件事的重點就在這裡。\""),
("slides_part2.py", "Gated DeltaNet 兩個都有 ——\n所以既能「快速清空」（α→0）也能「精準改寫」（β→1）。",
 "Gated DeltaNet 兩個都有，\n所以既能「快速清空」（α→0）也能「精準改寫」（β→1）。"),
("slides_part2.py", "recurrent 矩陣用 FP32 存 —— 這直接決定了 CH6 的 144 MiB。</li>",
 "recurrent 矩陣用 FP32 存，CH6 的 144 MiB 就是這樣來的。</li>"),
("slides_part2.py", "直接把 144 MiB 砍成 72 MiB —— 這是 CH6 會提到的一個實用旋鈕（但要驗證品質）。",
 "直接把 144 MiB 砍成 72 MiB。CH6 會提到這個旋鈕，但品質要先驗過。"),
("slides_part2.py", "\"兩者必須同步前進 —— 這是 hybrid 模型 serving 最容易出錯的地方。\"",
 "\"兩者要同步前進。hybrid 模型 serving 最容易出錯的地方就在這裡。\""),
("slides_part2.py", "兩者的 recurrent state 竟然都剛好是\n144 MiB —— 因為 36×64 = 48×48 = 2,304 個 value head。這個巧合很好記。",
 "兩者的 recurrent state 竟然都剛好是 144 MiB，\n因為 36×64 = 48×48 = 2,304 個 value head。這個巧合很好記。"),
("slides_part2.py", "\"chunk 之間只傳遞一個固定大小的狀態 S —— 唯一的序列依賴。\"",
 "\"chunk 之間只傳遞一個固定大小的狀態 S，序列依賴只剩這一條。\""),
("slides_part2.py", "這一頁常常是決策會議上最實用的一頁。它把「支援一個新模型」拆成七個具體項目，\n方便評估工作量與風險。",
 "決策會議上這一頁通常最實用。它把「支援一個新模型」拆成七個具體項目，\n工作量與風險比較好估。"),
("slides_part2.py", "混合架構的邏輯很直接：用 3/4 的層享受 O(1) 的好處，",
 "混合架構的想法很直接：用 3/4 的層享受 O(1) 的好處，"),
("slides_part2.py", "這是目前長 context 模型的主流做法。", "現在長 context 模型多半這樣做。"),
("slides_part2.py", "這一頁是第二版新增的內容，也是實務上最容易踩雷的地方。",
 "這一頁是第二版新增的，實務上也最容易踩雷。"),

# ============================================================ part 3 =====
("slides_part3.py", "量化不只是「檔案變小」——它決定了能不能單卡跑，也決定了哪些張量仍然是 BF16 的頻寬大戶。",
 "量化的影響不只是檔案變小。它決定能不能單卡跑，也決定哪些張量還留在 BF16 當頻寬大戶。"),
("slides_part3.py", "② 「4-bit 模型」實際上是 4.5 bit —— 算記憶體時要用 4.5。",
 "② 「4-bit 模型」實際上是 4.5 bit，算記憶體時要用 4.5。"),
("slides_part3.py", "所以不需要在 kernel 裡反量化再算 —— 這是它比軟體量化快的原因。",
 "所以不需要在 kernel 裡反量化再算，比軟體量化快的原因就在這。"),
("slides_part3.py", "保持 BF16 —— 這些是決定 decay gate 的參數，\n數值敏感度高，量化下去會直接壞掉。",
 "保持 BF16。這些是決定 decay gate 的參數，\n數值敏感度高，量化下去會直接壞掉。"),
("slides_part3.py", "GB —— \"\n      f\"這是「單卡跑得動」與「至少要兩張卡」的分界線。\")}",
 "GB。\"\n      f\"這正好是「單卡跑得動」與「至少要兩張卡」的分界線。\")}"),
("slides_part3.py", "就從 cache 預算裡扣掉 —— 相當於少放",
 "就從 cache 預算裡扣掉，相當於少放"),
("slides_part3.py", "<p>引文那句話也解釋了為什麼只有 routed expert 被量化 ——\n官方明確說只量化了 MoE 內部 transformer block 的線性算子。</p>",
 "<p>引文那句話也解釋了為什麼只有 routed expert 被量化：官方寫得很清楚，\n量化範圍是 MoE 內部 transformer block 的線性算子。</p>"),
("slides_part3.py", "不是由 KV cache 決定 —— 這與直覺相反，也是第一版報告漏掉的重點。",
 "不在 KV cache。這一點跟直覺相反，第一版報告也漏掉了。"),
("slides_part3.py", "MiB —— 但必須先驗證長 context 的品質。",
 "MiB，但長 context 的品質要先驗過。"),
("slides_part3.py", "MiB\n —— 佔比小，但這是「開 spec 會多吃記憶體」的一個具體來源。",
 "MiB。\n 佔比不大，但「開 spec 會多吃記憶體」有一部分就是它。"),
("slides_part3.py", "\"同時乘上 KV 與 SSM —— 短對話場景的主要旗標\"",
 "\"同時乘上 KV 與 SSM，短對話場景的主要旗標\""),
("slides_part3.py", "\"能承諾的容量由 CH9 的開環測試決定，\"\n       \"那個數字通常小得多。\"",
 "\"能承諾的容量由 CH9 的開環測試決定，那個數字通常小得多。\""),
("slides_part3.py", "\"輸出品質完全不變（rejection sampling 保證），但那塊算力不是無限的 —— \"\n \"這正是本章要量化的界線。\"",
 "\"輸出品質不變（rejection sampling 保證），但那塊算力有限，\"\n \"本章要量的就是那條界線。\""),
("slides_part3.py", "「用同一次權重讀取，多送幾個 token 進去」的另一種方法 ——\n和加大 batch 是同一件事的兩種做法。",
 "「用同一次權重讀取，多送幾個 token 進去」的另一種辦法，\n跟加大 batch 是同一件事的兩種做法。"),
("slides_part3.py", "① <b>「猜錯會讓品質變差」</b>——不會。rejection sampling 在數學上保證輸出分布不變，",
 "① <b>「猜錯會讓品質變差」</b>：不會。rejection sampling 在數學上保證輸出分布不變，"),
("slides_part3.py", "② <b>「最壞情況會比不猜慢」</b>——就 <b>token 數</b>而言不會（一定前進 1 格），",
 "② <b>「最壞情況會比不猜慢」</b>：就 <b>token 數</b>而言不會（一定前進 1 格），"),
("slides_part3.py", "③ <b>「被拒絕的位置後面那些草稿還可以留著」</b>——不行，它們是以錯誤前綴為條件產生的。",
 "③ <b>「被拒絕的位置後面那些草稿還可以留著」</b>：不行，它們是以錯誤前綴為條件產生的。"),
("slides_part3.py", "\"<b>絕對 tok/s 與加速倍數不行</b> —— 那會隨 GPU、量化與併發改變。上線前必須自己量。\"",
 "\"<b>絕對 tok/s 與加速倍數不行</b>，那會隨 GPU、量化與併發改變。上線前要自己量一次。\""),
("slides_part3.py", "唯一的代價是驗證時要多算 token —— 這正好對應到下一頁的屋頂線分析。",
 "代價是驗證時要多算 token，正好接到下一頁的屋頂線分析。"),
("slides_part3.py", "\"<b>122B + MTP (k=3)</b>：形狀完全不同 —— 因為它是 MoE。低併發時 spec 的優勢被\"",
 "\"<b>122B + MTP (k=3)</b>：形狀完全不同，因為它是 MoE。低併發時 spec 的優勢被\""),
("slides_part3.py", "壓到中段突然變差 —— 因為越過了這條線。",
 "壓到中段突然變差，就是越過了這條線。"),
("slides_part3.py", "核對<b>你安裝的版本</b>的旗標名稱 —— \"\n      \"speculative decoding 的介面在最近幾個版本改動頻繁。",
 "核對<b>你安裝的版本</b>的旗標名稱，\"\n      \"speculative decoding 的介面最近幾個版本改動頻繁。"),
("slides_part3.py", "這一頁是全章的核心，也是回答「speculative decoding 對 serving 的影響」\n最直接的一張圖。",
 "這一頁是全章最重要的一張圖，也最直接回答「speculative decoding 對 serving 的影響」。"),
("slides_part3.py", "這一頁是整章的行動結論，可以直接印出來當 checklist。",
 "這一頁可以直接印出來當 checklist。"),
("slides_part3.py", "這是全章最重要的實務警告，而且有公開的實測資料支撐。",
 "這是全章最該記住的實務警告，而且有公開實測資料撐著。"),
("slides_part3.py", "這一頁是整份報告最有價值的發現之一，而且完全可驗證。",
 "這一頁的發現大概是整份報告裡最有價值的，而且可以自己驗。"),
("slides_part3.py", "這一章是第二版新增。第一版報告假設 BF16，所有記憶體數字都偏大 2–3 倍。",
 "這一章是第二版新增的。第一版假設 BF16，記憶體數字全部偏大 2–3 倍。"),
("slides_part3.py", "這一章回應了「記憶體配置試算要分開看 SSM Cache 跟 KV Cache」這個需求。",
 "這一章就是把 SSM cache 跟 KV cache 分開算。"),
("slides_part3.py", "這一整章是第二版新增，也是這份報告最實用的部分。",
 "這一整章是第二版新增的，大概也是最實用的一章。"),
("slides_part3.py", "這一頁是這一章最有行動力的一頁。它把「該調哪個旗標」跟 workload 直接連起來。",
 "這一頁把「該調哪個旗標」直接接到 workload 上，最好用。"),
("slides_part3.py", "這一頁直接回應了「記憶體配置試算要分開看 SSM Cache 跟 KV Cache」。\n兩條公式都寫出來了，而且 conv state 的 <code>num_spec</code> 項就是 CH7 的伏筆。",
 "兩條公式都寫出來了。conv state 那條裡的 <code>num_spec</code> 是 CH7 的伏筆。"),
("slides_part3.py", "教訓：長 context 服務一定要重新量接受率，不能沿用短 prompt 的結論。",
 "長 context 服務要重新量接受率，短 prompt 的結論搬不過來。"),

# ============================================================ part 4 =====
("slides_part4.py", "母體是「每一個 request」—— 與 ITL 不同。",
 "母體是「每一個 request」，與 ITL 不同。"),
("slides_part4.py", "而 TPOT 看起來還好 —— \"\n   \"只看 TPOT 會誤判系統健康。",
 "而 TPOT 看起來還好。\"\n   \"只看 TPOT 會誤判系統健康。"),
("slides_part4.py", "但沒有一個人滿足 SLO —— 這時 goodput = 0。",
 "但沒有一個人滿足 SLO，此時 goodput = 0。"),
("slides_part4.py", "\"但 p95 與 p99 在尾巴上 —— 而那些人就是會抱怨的人。\"",
 "\"但 p95 與 p99 在尾巴上，而那些人就是會來抱怨的人。\""),
("slides_part4.py", "但 p95 TTFT 從 600 ms 變成 4,000 ms —— goodput 反而從 5,800 掉到 0。",
 "但 p95 TTFT 從 600 ms 變成 4,000 ms，goodput 反而從 5,800 掉到 0。"),
("slides_part4.py", "看 throughput 什麼時候不再成長 —— 那就是這台機器的物理極限。",
 "看 throughput 什麼時候不再成長，那裡就是這台機器的物理極限。"),
("slides_part4.py", "① throughput 開始飽和的併發數 —— 對照 CH1 的 N* ≈ {KNEE:.0f}；",
 "① throughput 開始飽和的併發數，對照 CH1 的 N* ≈ {KNEE:.0f}；"),
("slides_part4.py", "\"先畫出 SLO 那條水平線 —— 沒有 SLO 就沒有容量。\"",
 "\"先畫出 SLO 那條水平線。沒講定 SLO，就談不上容量。\""),
("slides_part4.py", "① 只跑一次就下結論 —— 邊界點的變異最大。<br>\n② 用平均值而不是 p95 —— 邊界會被高估。<br>",
 "① 只跑一次就下結論，而邊界點的變異最大。<br>\n② 用平均值取代 p95，邊界會被高估。<br>"),
("slides_part4.py", "<tr><td>思考模式</td><td>thinking 開／關 —— 會大幅改變輸出長度</td></tr>",
 "<tr><td>思考模式</td><td>thinking 開／關，會大幅改變輸出長度</td></tr>"),
("slides_part4.py", "短對話時它<b>主導</b>記憶體 —— 122B 要到",
 "短對話時它<b>主導</b>記憶體：122B 要到"),
("slides_part4.py", "\"先確認症狀是什麼 —— 別在沒看指標之前就開始調參數。\"",
 "\"先確認症狀是什麼。別在沒看指標之前就開始調參數。\""),
("slides_part4.py", "\"<b>常常 preempt</b>：問題在 cache 不夠 —— 這是容量問題，不是效能問題。\"",
 "\"<b>常常 preempt</b>：問題在 cache 不夠。這屬於容量問題，不是效能問題。\""),
("slides_part4.py", "<li>多模態（視覺塔）的容量影響 —— 只在參數帳本裡列出大小</li>",
 "<li>多模態（視覺塔）的容量影響，只在參數帳本裡列出大小</li>"),
("slides_part4.py", "\"NVFP4 讓 122B 可以走 DP 而不是 TP —— 這是本次評估最重要的工程結論之一。\"",
 "\"NVFP4 讓 122B 可以走 DP 取代 TP。這算本次評估最重要的工程結論之一。\""),
("slides_part4.py", "vLLM 會複製它們 —— 每張卡的 KV cache 不會再變小。\n這讓 TP=8 對 122B 特別不划算。",
 "vLLM 會複製它們，每張卡的 KV cache 不會再變小。\nTP=8 對 122B 因此特別不划算。"),
("slides_part4.py", "這是負載測試最常見的方法論錯誤。閉環測試（大多數工具的預設）\n會讓系統看起來永遠很穩定，因為 client 在幫伺服器限流。",
 "負載測試最常見的方法論錯誤就是這個。閉環測試（大多數工具的預設）\n會讓系統看起來一直很穩，因為 client 在幫伺服器限流。"),
("slides_part4.py", "誠實列出邊界會提高整份報告的可信度。",
 "把邊界寫清楚，報告才站得住。"),
("slides_part4.py", "要強調第四支：preempt 是<b>容量</b>訊號不是效能訊號。\n看到 preempt 就不該再想「怎麼調快」，而該想「是不是不該收這麼多請求」。",
 "第四支要特別講：preempt 是<b>容量</b>訊號，不是效能訊號。\n看到 preempt 就別再想「怎麼調快」，該想的是「是不是不該收這麼多請求」。"),
("slides_part4.py", "這一頁可以直接當成團隊的指標定義規範。",
 "這一頁可以直接拿去當團隊的指標定義規範。"),
("slides_part4.py", "這一頁可以直接當成報告模板的目錄。",
 "這一頁可以直接拿去當報告模板的目錄。"),
("slides_part4.py", "這一章比較短但很關鍵。建議要求所有人用同一份定義寫報告。",
 "這一章短，但值得要求所有人用同一份定義寫報告。"),
("slides_part4.py", "這一章的產出物是一份可以被別人重跑的測試報告，不是一個最高 tok/s 的數字。",
 "這一章要交出來的是一份別人可以重跑的測試報告，而不是一個最高 tok/s 的數字。"),

# ======================================================== widgets.js =====
("widgets.js", "'延遲隨併發單調上升，永遠不會爆掉 —— 所以閉環量不到容量'",
 "'延遲隨併發單調上升，不會爆掉，所以閉環量不到容量'"),
]

if __name__ == "__main__":
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8")
    c, m = apply(R)
    print(f"applied {c} / {len(R)}")
    for fn, frag in m:
        print("  MISS", fn, frag)
